### ISSUE TITLE
Error if required Subject field is not found in LabTracks

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#10]
**Describe the bug**
If the LabTracks can't find a value for a field required by Subject schema, then an error is thrown.

**To Reproduce**
~1. Run `curl -X GET http://localhost:5000 -d specimen_id=303220 -G`~
1. Run `curl -X GET http://localhost:5000/subject/303220`
2. On the client side, the error just says: `Internal Server Error`
3. On the server side, the stack trace is:
```
INFO:     172.17.0.1:37964 - "GET /subject/303220 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/server.py", line 39, in retrieve_subject
    handled_response = lb_client.handle_response(lb_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/labtracks/client.py", line 123, in handle_response
    handled_response = lth.map_response_to_subject(response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/labtracks/client.py", line 258, in map_response_to_subject
    subject = Subject(
              ^^^^^^^^
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Subject
genotype
  none is not an allowed value (type=type_error.none.not_allowed)
background_strain
  value is not a valid enumeration member; permitted: 'C57BL/6J', 'BALB/c' (type=type_error.enum; enum_values=[<BackgroundStrain.C57BL_6J: 'C57BL/6J'>, <BackgroundStrain.BALB_c: 'BALB/c'>])
```
4. Run a get request where the subject id doesn't exist: `curl -X GET http://localhost:5000/subject/0000`
5. The client side says `Internal Server Error`. The server side has the stack trace:
```
INFO:     172.17.0.1:37970 - "GET /subject/0000 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/server.py", line 39, in retrieve_subject
    handled_response = lb_client.handle_response(lb_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/labtracks/client.py", line 123, in handle_response
    handled_response = lth.map_response_to_subject(response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aind_metadata_service/labtracks/client.py", line 236, in map_response_to_subject
    contents = response["msg"][0]
               ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
**Expected behavior**

1. If the ID does not exist, return `{ 'status': 'error', 'error': 'subject <id> not found', data: null }`
2. If the ID exists but does not validate, return `{ 'status': 'error', 'error': 'subject <id> missing required fields', 'validation_errors': "...", 'data': { ... } }`
3. If the ID exists and validates, return `{ 'status': 'ok', 'data': { ... } }`

For data that does not validate, attempt to populate `data` with all metadata available and fill in `null`s for missing fields.

**Additional context**

**Comment by jtyoung84** [comment]
We can follow the example in: https://fastapi.tiangolo.com/tutorial/handling-errors/

In case of no errors, just return the data (FastAPI should give it a status_code of 200 out of the box I think)
In case of an error return a JsonResonse such as

```
return JSONResponse(status_code=418, 
  content={"message": f"An error", "data": {}})
```

**Comment by mekhlakapoor** [comment]
If the ID does not exist, returns `{'message': 'Error finding subject: subject 0000 does not exist', 'data': {'msg': []}}`
